name: Build AuricM v1 APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk

    # Step 3: Install Python dependencies
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython buildozer kivy kivymd mutagen yt_dlp pygame requests pillow

    # Step 4: Dynamically configure Buildozer
    - name: Configure Buildozer
      run: |
        # Set app title
        sed -i 's/^title = .*/title = AuricM v1/' buildozer.spec
        # Set package name (must be lowercase, no spaces)
        sed -i 's/^package.name = .*/package.name = com.userballs.auricmv1/' buildozer.spec
        # Ensure all required dependencies
        sed -i 's/^requirements = .*/requirements = python3,kivy,kivymd,mutagen,yt_dlp,requests,pygame,pillow/' buildozer.spec
        # Set orientation
        sed -i 's/^orientation = .*/orientation = portrait/' buildozer.spec

    # Step 5: Build the APK
    - name: Build APK
      run: |
        buildozer android debug

    # Step 6: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AuricM-v1-APK
        path: bin/*.apk
